name: 'PR Label Regex Match'
description: 'Get a list of PR labels that matches a given regex'
author: 'Frank Gu <frank@voiceflow.com>'
inputs:
  regex:              
    description: 'Regex expression for PR labels'
    default: '.*' # Match everthing
    required: true
outputs: 
  multiple: 
    description: Are there multiple labels matching the regex? 
  label: 
    description: The first label matching the regex (order is not guaranteed!); empty if no matches
runs:
  using: 'node12'
  main: 'dist/index.js'
